<a href="https://colab.research.google.com/github/KBVYSHNAVI/Python/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(3,)

In [ ]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.linspace(0,1,5) #starting number,last number,numbers between them
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.logspace(1,3,3) #logarithmic scale array
print(arr)

[  10.  100. 1000.]


In [ ]:
#np.zeroes -> array full of zeroes
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr = np.zeros([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.ones([4,2],dtype = int) #array full of ones
print(arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
arr = np.full(10,2)#creates an array full of any value
print(arr)

[2 2 2 2 2 2 2 2 2 2]


In [ ]:
arr = np.full([2,4],7.1) #[row,column],default value
print(arr)

[[7.1 7.1 7.1 7.1]
 [7.1 7.1 7.1 7.1]]


In [ ]:
arr = np.random.rand(10)
print(arr)

[0.40225809 0.0510876  0.50686786 0.24128125 0.33723955 0.02886467
 0.02830834 0.16486922 0.87378926 0.58247466]


In [ ]:
arr = np.random.rand(2,3)
print(arr)

[[0.73428423 0.61766241 0.34863794]
 [0.34590569 0.71696834 0.47577516]]


In [ ]:
arr = np.random.randn(2,3)
print(arr) # random floats from standard normal distribution

[[ 0.00585715 -0.28364751 -1.23398366]
 [ 0.13390249 -0.51599694 -1.85009055]]


In [ ]:
arr = np.random.randint(10,100)
print(arr) # random integer

27


In [ ]:
arr = np.random.randint(10,100,size = (2,3))
print(arr)

[[64 34 96]
 [36 36 75]]


Numpy Data Types and Type Casting

In [ ]:
arr = np.array([1,2,3.1,4,5])
print(arr)

[1.  2.  3.1 4.  5. ]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst = ["string",1,2,5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [ ]:
arr = np.array([1,2,3,4], dtype = np.float64)
print(arr)


[1. 2. 3. 4.]


In [ ]:
arr.dtype

dtype('float64')

Type casting


In [ ]:
#type casting -> astype()

In [ ]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
newarr = arr.astype(np.float64)
newarr

array([1., 2., 3.])

In [ ]:
newarr.dtype

dtype('float64')

In [ ]:
newarr2 = newarr.astype(np.int64)
newarr2

array([1, 2, 3])

Type casting errors

In [ ]:
arr = np.array[1,2,"hello"]
#strings are not converted into int or float

Array reshaping #reshape #ravel #flatten


In [ ]:
#reshape

Arithemetic Operators on array

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
#addition
print(a+b)

[5 7 9]


In [ ]:
print(b-a)

[3 3 3]


In [ ]:
print(a/b)#normal divison

[0.25 0.4  0.5 ]


In [ ]:
print(b//a) #integer division

[4 2 2]


In [ ]:
#multiplication
print(a*b)

[ 4 10 18]


In [ ]:
#modulus ->gives remainder
print(b % a)

[0 1 0]


In [ ]:
#exponents ->power
print(a ** 2)

[1 4 9]


Universal Functions ->ufuncs

In [ ]:
arr = np.array([1,4,9,16])

In [ ]:
#squareroot ->np.sqrt
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
#exponential ->np.exp->e^x->x is any integer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
#sine function ->np.sin
angles = np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


Indexing and slicing

In [ ]:
a = [1,2,3,4,5]

In [ ]:
a[-1:-4:-1]

[5, 4, 3]

In [ ]:
a[: : 2]

[1, 3, 5]

In [ ]:
arr = np.array([10,20,30,40,50])
#indexes = 0,2,4
arr[: : 2]


array([10, 30, 50])

In [ ]:
#negeative indexing
print(arr[-1])

50


In [ ]:
#multidimensional array
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [ ]:
print(matrix[0:2,:])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(matrix[1: , 1: ])

[[5 6]
 [8 9]]


In [ ]:
#np.take -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr,ind))

[10 30]


In [ ]:
#Iterating with nditer()

In [ ]:
arr = np.array([[1,2],[3,4]])

In [ ]:
for x in np.nditer(arr):
  print(x,end = " ")

1 2 3 4 

In [ ]:
#ndenumerate() -> both index + value
for ind, x in  np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
#Views vs copies
#view = original array will be affected
#copies = original array will be unchanges


In [ ]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [ ]:
view[0] = 200

In [ ]:
view

array([200,   3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
#copy
copy = arr[1:3].copy()
copy


array([200,   3])

In [ ]:
copy[0] = 2
copy

array([2, 3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
#Transpose->which swaps rows and columns
print(arr.transpose())

[[1 3]
 [2 4]]


In [ ]:
#swapaxes -> swap 2 specific axes in a matrix
arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap = np.swapaxes(arr,0,1)
swap.shape


(2, 1, 2)

In [ ]:
#concatenation
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [ ]:
print(np.vstack((a1,a2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(np.hstack((a1,a2)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.stack((a1,a2),axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(np.stack((a1,a2),axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
#Splitting the array -> Only equal division parts
arr1 = np.array([[1,2],[3,4],[5,6],[7,8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
print(np.split(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
print(np.hsplit(arr1,2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [ ]:
print(np.vsplit(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
#Repeating ->repeats each element
arr = np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
#tile ->repeats the whole array
print(np.tile(arr,2))

[1 2 3 1 2 3]


In [ ]:
#aggregate functions
arr = np.array([1,2,3])
print(np.sum(arr))

6


In [ ]:
print(np.mean(arr))

2.0


In [ ]:
print(np.median(arr))

2.0


In [ ]:
np.std(arr)

np.float64(0.816496580927726)

In [ ]:
np.var(arr)

np.float64(0.6666666666666666)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.max(arr)

np.int64(3)

In [18]:
matrix

NameError: name 'matrix' is not defined

In [ ]:
print(np.sum(matrix,axis = 1)) #column wise operations

[ 6 15 24]


In [ ]:
print(np.sum(matrix,axis = 0)) #row wise operations

[12 15 18]


In [ ]:
arr

array([1, 2, 3])

In [ ]:
#Cumulative operations -> running total
print(np.cumsum(arr))

[1 3 6]


In [ ]:
print(np.cumprod(arr))

[1 2 6]


***conditional based choices***

In [6]:
#where
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
result = np.where(arr<2,"low","high")

In [8]:
result

array(['low', 'high', 'high'], dtype='<U4')

In [10]:
arr #argwhere :row-column positions for 2d arrays

array([1, 2, 3])

In [13]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [14]:
print(np.argwhere(arr>20))

[[2]
 [3]
 [4]]


In [15]:
mask = np.logical_and(arr>15,arr<35)

In [16]:
mask


array([False,  True,  True, False, False])

In [20]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                   [7,8,9]]);


In [21]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print(np.argwhere(matrix>5)) #it returns the row and column indices whenever it satisfies the condition

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [32]:
#Logical and
arr = np.array([100,2,3,4,5,6])
arr

array([100,   2,   3,   4,   5,   6])

In [34]:
mask = np.logical_and(arr>3,arr<6)

In [35]:
arr[mask]

array([4, 5])

In [36]:
#logical or
mask = np.logical_or(arr<4,arr>5)

In [37]:
arr[mask]

array([100,   2,   3,   6])

In [39]:
arr2 = np.array([0,1,5,0,5])
arr2

array([0, 1, 5, 0, 5])

In [40]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [ ]:
#broadcasting =>

In [43]:
image = np.array([[200,150],[100,250]])
image.shape

(2, 2)

In [42]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [ ]:
#vectorization
#np.vectorize()->convert a regular function to be applied on an array


In [45]:
def square(x):
  return x*x
vfunc = np.vectorize(square)

In [46]:
arr

array([100,   2,   3,   4,   5,   6])

In [47]:
print(vfunc(arr))

[10000     4     9    16    25    36]


In [ ]:
#dealing with missing values

#np.nan -> not a number this is used to represent missing or undefined number


In [48]:
a = np.array([1,2,np.nan,4])

In [49]:
a

array([ 1.,  2., nan,  4.])

In [ ]:
#np.inf and -np.inf -> this represent positive and negitive values
#they often appears where incses of division/0 or overflow questions

In [ ]:
#np.isnan
#np.isinf
#np.isfinite
#--->these are the functions used to detect any null values,infinite value or finite value

In [50]:
print(np.isnan(a))

[False False  True False]


In [52]:
b = np.array([1,np.nan,np.inf,10.2,40])

In [53]:
print(np.isinf(b))

[False False  True False False]


In [54]:
print(np.isfinite(b))

[ True False False  True  True]


In [55]:
new_b = np.nan_to_num(b) # remove nan/infinite values

In [56]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])